server:
  port: 8012

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://gitlab.steedos.cn/sundalei/photoappconfiguration.git
          username: sundalei
          password: oarnud9I
          clone-on-start: true
          default-label: main

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: 'busrefresh'

