server:
  port: 0

spring:
  application:
    name: account-ws

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8010/eureka"