server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-status-check
          uri: lb://users-ws
          predicates:
            - Path=/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
#            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8010/eureka"

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug
